name: Continuous Integration

on: [push, pull_request]

jobs:
  phpstan:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Install dependencies"
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Run PHPStan"
        run: php7.3 vendor/bin/phpstan analyze -c phpstan.neon.dist --no-interaction --no-progress

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Install dependencies"
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Run PHPUnit"
        run: php7.3 vendor/bin/phpunit -c phpunit.xml.dist

  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Install dependencies"
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Build Code Coverage Report"
        run: php7.3 vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=./build/coverage.xml --log-junit=./build/test-report.xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/coverage.xml
